foreground   #f6eae1
background   #020202
cursor       #f6eae1

color0       #020202
color8       #aca39d
color1       #DB8FC6
color9       #DB8FC6
color2       #E699D0
color10      #E699D0
color3       #F8ABD7
color11      #F8ABD7
color4       #FDB1E7
color12      #FDB1E7
color5       #FFB2E9
color13      #FFB2E9
color6       #FFB2E9
color14      #FFB2E9
color7       #f6eae1
color15      #f6eae1
