# Blue light filter
bind = $mainMod, I, exec, hyprctl hyprsunset temperature 5000
bind = $mainMod, O, exec, hyprctl hyprsunset identity

# Philips Hue lights
bind = $mainMod SHIFT, I, exec, openhue set scene Trans.bg
bind = $mainMod SHIFT, O, exec, openhue set room Chambre --off

# Discord Workspace
bind = $mainMod, S, togglespecialworkspace, discord
bind = $mainMod SHIFT, S, movetoworkspace, special:discord
