# Blue light filter
bind = $mainMod, O, exec, hyprctl hyprsunset temperature 5000
bind = $mainMod, I, exec, hyprctl hyprsunset identity

# Discord Workspace
bind = $mainMod, S, togglespecialworkspace, discord
bind = $mainMod SHIFT, S, movetoworkspace, special:discord
