# Automatically put Discord in special workspace
windowrule {
  name = discord-window-rule
  workspace = special:discord
  match:class = ^vesktop$
}


# Workspace style
workspace = special:discord, gapsout:15, gapsin:15
