# Automatically put Spotify in music center
windowrule {
  name = windowrule-7
  workspace = special:musiccenter
  match:class = ^spotify$
}

# Control center Workspace
bind = $mainMod, P, togglespecialworkspace, musiccenter
bind = $mainMod SHIFT, P, movetoworkspace, special:musiccenter

# Workspace style
workspace = special:musiccenter, gapsout:60, gapsin:60
