# fix jetbrains focus issues
# fix tooltips (always have a title of `win.<id>`)
windowrule {
  name = windowrule-3
  no_initial_focus = on
  no_focus = on
  match:class = ^(.*jetbrains.*)$
  match:title = ^(win.*)$
}

# fix tab dragging (always have a single space character as their title)
windowrule {
  name = windowrule-4
  no_initial_focus = on
  no_focus = on
  match:class = ^(.*jetbrains.*)$
  match:title = ^\\s$
}


# prevent Steam from floating
windowrule {
  name = windowrule-5
  tile = on
  match:class = ^steam$
}
